/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    get: {
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/guilds": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.guilds.id"];
          created_at?: parameters["rowFilter.guilds.created_at"];
          plan?: parameters["rowFilter.guilds.plan"];
          name?: parameters["rowFilter.guilds.name"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["guilds"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** guilds */
          guilds?: definitions["guilds"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.guilds.id"];
          created_at?: parameters["rowFilter.guilds.created_at"];
          plan?: parameters["rowFilter.guilds.plan"];
          name?: parameters["rowFilter.guilds.name"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.guilds.id"];
          created_at?: parameters["rowFilter.guilds.created_at"];
          plan?: parameters["rowFilter.guilds.plan"];
          name?: parameters["rowFilter.guilds.name"];
        };
        body: {
          /** guilds */
          guilds?: definitions["guilds"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/hoots": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.hoots.id"];
          created_at?: parameters["rowFilter.hoots.created_at"];
          url?: parameters["rowFilter.hoots.url"];
          start?: parameters["rowFilter.hoots.start"];
          end?: parameters["rowFilter.hoots.end"];
          name?: parameters["rowFilter.hoots.name"];
          guildId?: parameters["rowFilter.hoots.guildId"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["hoots"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** hoots */
          hoots?: definitions["hoots"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.hoots.id"];
          created_at?: parameters["rowFilter.hoots.created_at"];
          url?: parameters["rowFilter.hoots.url"];
          start?: parameters["rowFilter.hoots.start"];
          end?: parameters["rowFilter.hoots.end"];
          name?: parameters["rowFilter.hoots.name"];
          guildId?: parameters["rowFilter.hoots.guildId"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.hoots.id"];
          created_at?: parameters["rowFilter.hoots.created_at"];
          url?: parameters["rowFilter.hoots.url"];
          start?: parameters["rowFilter.hoots.start"];
          end?: parameters["rowFilter.hoots.end"];
          name?: parameters["rowFilter.hoots.name"];
          guildId?: parameters["rowFilter.hoots.guildId"];
        };
        body: {
          /** hoots */
          hoots?: definitions["hoots"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
}

export interface definitions {
  /** @description Discord Guild */
  guilds: {
    /**
     * Format: text
     * @description Note:
     * This is a Primary Key.<pk/>
     * @default
     */
    id: string;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    created_at?: string;
    /**
     * Format: text
     * @default BASIC
     */
    plan?: string;
    /** Format: text */
    name: string;
  };
  /** @description list of hoots */
  hoots: {
    /**
     * Format: text
     * @description Note:
     * This is a Primary Key.<pk/>
     * @default
     */
    id: string;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    created_at?: string;
    /** Format: text */
    url: string;
    /** Format: bigint */
    start: number;
    /** Format: bigint */
    end: number;
    /** Format: text */
    name: string;
    /**
     * Format: text
     * @description Note:
     * This is a Foreign Key to `guilds.id`.<fk table='guilds' column='id'/>
     */
    guildId: string;
  };
}

export interface parameters {
  /**
   * @description Preference
   * @enum {string}
   */
  preferParams: "params=single-object";
  /**
   * @description Preference
   * @enum {string}
   */
  preferReturn: "return=representation" | "return=minimal" | "return=none";
  /**
   * @description Preference
   * @enum {string}
   */
  preferCount: "count=none";
  /** @description Filtering Columns */
  select: string;
  /** @description On Conflict */
  on_conflict: string;
  /** @description Ordering */
  order: string;
  /** @description Limiting and Pagination */
  range: string;
  /**
   * @description Limiting and Pagination
   * @default items
   */
  rangeUnit: string;
  /** @description Limiting and Pagination */
  offset: string;
  /** @description Limiting and Pagination */
  limit: string;
  /** @description guilds */
  "body.guilds": definitions["guilds"];
  /** Format: text */
  "rowFilter.guilds.id": string;
  /** Format: timestamp with time zone */
  "rowFilter.guilds.created_at": string;
  /** Format: text */
  "rowFilter.guilds.plan": string;
  /** Format: text */
  "rowFilter.guilds.name": string;
  /** @description hoots */
  "body.hoots": definitions["hoots"];
  /** Format: text */
  "rowFilter.hoots.id": string;
  /** Format: timestamp with time zone */
  "rowFilter.hoots.created_at": string;
  /** Format: text */
  "rowFilter.hoots.url": string;
  /** Format: bigint */
  "rowFilter.hoots.start": string;
  /** Format: bigint */
  "rowFilter.hoots.end": string;
  /** Format: text */
  "rowFilter.hoots.name": string;
  /** Format: text */
  "rowFilter.hoots.guildId": string;
}

export interface operations {}

export interface external {}
